### ISSUE TITLE
Proofread!

### ISSUE THREAD

**Issue by noplanman** [10up/Engineering-Best-Practices#178]
Right, I have finally finished proofreading this great resource and am super grateful for all the things I was able to learn along the way! 😃 

To make this easier to digest (as there are quite a few changes), I've split this up into a few different PRs, allowing reviewing and inline commenting to be much easier on each PR itself.

To keep everything in check, here the list of PRs and their content:
- [x] #179 - Typos (purely a bunch of typos)
- [x] #180 - HTTPS-ification (Changing all HTTP links to HTTPS where applicable, fixing broken/updated links along the way)
- [ ] #181 - Code fixes (Prettify/fix code examples, to also adhere to coding standards)
- [x] #182 - Grammar (some changes to grammar and wording)
- [ ] #183 - Headings/Menus (Adding "Back to top" links on all h2 headings; Adding them to the main menu? [discuss on PR])
- [ ] #184 - Other changes (Little things to round off the prettiness)

I think it would be easiest to go through them point by point, merging each one from the top down to reduce any conflicts. I've set them up so that this should work very easily, starting with the point that needs least discussion/reviewing.

**Improve all the things!** 😇

Obviously they are all open to discussion an scrutiny!

**Comment by noplanman** [comment]
Have rebased all PRs to include typos merge. 👍

**Comment by dana-ross** [comment]
All these PRs were merged or closed. Closing this issue. Thanks for contributing!
